name: CI/CD for Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Archive production artifacts
        run: tar -czf build.tar.gz -C dist/frontend .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy artifact to EC2
        run: |
          scp build.tar.gz ec2-user@ec2-3-137-147-107.us-east-2.compute.amazonaws.com:/home/ec2-user/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-public-dns << 'EOF'
            cd /var/www/html
            rm -rf *
            tar -xzf /home/ec2-user/build.tar.gz -C .
            rm /home/ec2-user/build.tar.gz
          EOF
